# Generated by Django 2.1.3 on 2018-11-21 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_semana',
            field=models.CharField(choices=[('SEGUNDA-FEIRA', 'Segunda-feira'), ('TERÇA-FEIRA', 'Terça-feira'), ('QUARTA-FEIRA', 'Quarta-feira'), ('QUINTA-FEIRA', 'Quinta-feira'), ('SEXTA-FEIRA', 'Sexta-feira'), ('SÁBADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=15, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='duracao',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='carga_horaria',
            field=models.TimeField(blank=True, null=True, verbose_name='Carga horária'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
